# Generated by Django 2.0.2 on 2018-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
    ]
