# Generated by Django 2.0.3 on 2018-03-07 09:18

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0002_event_is_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorful.fields.RGBColorField(default='#FF0000', verbose_name='Цвет маркера на карте'),
        ),
    ]
