# Generated by Django 2.0.3 on 2018-03-07 14:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0003_auto_20180307_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
