# Generated by Django 2.0.3 on 2018-03-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0010_auto_20180312_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mit_calendar.Place', verbose_name='Место проведения'),
        ),
    ]
