# Generated by Django 2.0.3 on 2018-03-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0012_auto_20180313_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, help_text='Принудительно запретить возможность регистрации посетителей на мероприятие, в незавсимости от кол-ва уже зарегистрированных персон.', verbose_name='Закрыть возможность регистрации'),
        ),
    ]
