# Generated by Django 2.0.3 on 2018-03-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0013_event_registration_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date', 'time'), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
