# Generated by Django 2.0.3 on 2018-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0014_auto_20180313_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_full_visitors',
            field=models.BooleanField(default=False, help_text='Работает только если включена галочка "Закрыть возможность регистрации"', verbose_name='Показывать полную заполненность зрителями'),
        ),
    ]
