# Generated by Django 2.0.3 on 2018-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mit_calendar', '0015_event_show_full_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='for_archive',
            field=models.BooleanField(default=True, help_text='Фотографии из фотоархива можно "лайкать"', verbose_name='Для фотоархива'),
        ),
    ]
