# Generated by Django 2.0.3 on 2018-03-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mit_calendar', '0013_event_registration_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('ip', models.GenericIPAddressField(verbose_name='IP адрес лайкнувшего')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mit_calendar.EventPhoto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
