# Generated by Django 2.0.3 on 2018-03-10 10:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater', '0003_personplayrole_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article_title', models.CharField(max_length=255, verbose_name='Заголовок блока статьи')),
                ('article_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст блока статьи')),
                ('team_title', models.CharField(max_length=255, verbose_name='Заголовок блока команды')),
                ('team_text', models.TextField(blank=True, null=True, verbose_name='Текст блока команды')),
            ],
            options={
                'verbose_name': 'Данные страницы',
                'verbose_name_plural': 'Данные страницы',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(help_text='Оптимальный размер: 200px*100px.', upload_to='partners', verbose_name='Изображение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='about',
            name='partners',
            field=models.ManyToManyField(to='about.Partner', verbose_name='Партнёры'),
        ),
        migrations.AddField(
            model_name='about',
            name='persons',
            field=models.ManyToManyField(to='theater.Person', verbose_name='Команда'),
        ),
    ]
