# Generated by Django 2.0.3 on 2018-03-09 15:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные страницы',
                'verbose_name_plural': 'Данные страницы',
            },
        ),
        migrations.CreateModel(
            name='ContactFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(1, 'Телефон'), (2, 'E-Mail')], verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контактные данные в "подвале"',
            },
        ),
    ]
