# Generated by Django 2.0.3 on 2018-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('vk', models.URLField(blank=True, max_length=255, null=True, verbose_name='Вконтакте')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('ok', models.URLField(blank=True, max_length=255, null=True, verbose_name='Одноклассники')),
                ('twitter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('youtube', models.URLField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Ссылки на соц. сети',
                'verbose_name_plural': 'Ссылки на соц. сети',
            },
        ),
    ]
