# Generated by Django 2.0.3 on 2018-03-10 11:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('promo_left', models.TextField(blank=True, null=True, verbose_name='Левая часть (HTML)')),
                ('promo_right', models.TextField(blank=True, null=True, verbose_name='Правая часть (HTML)')),
                ('icon1_icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('icon1_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon1_text', models.TextField(verbose_name='Текст')),
                ('icon2_icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('icon2_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon2_text', models.TextField(verbose_name='Текст')),
                ('icon3_icon', models.CharField(max_length=255, verbose_name='Иконка')),
                ('icon3_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon3_text', models.TextField(verbose_name='Текст')),
                ('about_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные страницы',
                'verbose_name_plural': 'Данные страницы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(help_text='Оптимальный размер: 900px*600px.', upload_to='home', verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Home', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
