# Generated by Django 2.0.2 on 2018-03-05 15:29

import apps.theater.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, help_text='Оптимальный размер: 400px*450px.', null=True, upload_to='people/', verbose_name='Фото')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PersonPlayRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='Роль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Person', verbose_name='Актёр')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег h1 (мета-тег)')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (мета-тег)')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords (мета-тег)')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Description (мета-тег)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('duration', models.DurationField(blank=True, help_text='Используйте формат ЧЧ:ММ:СС', null=True, verbose_name='Продолжительность')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PlayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(help_text='Оптимальный размер: 800px*500px.', upload_to=apps.theater.models.PlayPhoto.upload_to, verbose_name='Изображение')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='PlayProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlayVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('youtube_id', models.CharField(help_text='Например, для видео https://www.youtube.com/watch?v=JMJXvsCLu6, его идентификатором будет JMJXvsCLu6.', max_length=32, verbose_name='Идентификатор на Youtube')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включено')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='personplayrole',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Play', verbose_name='Спектакль'),
        ),
    ]
