# Generated by Django 2.0.2 on 2018-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_auto_20180306_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='personplayrole',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткий текст'),
        ),
    ]
