# Generated by Django 2.0.3 on 2018-03-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180309_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_visible',
            new_name='is_enabled',
        ),
    ]
