# Generated by Django 2.0.3 on 2018-03-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_publish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
